name: Example Workflow

on:
  pull_request:
    branches:
      - 'test/*'

jobs:
  build:
    name: Deployment for Develop environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --production # will run `yarn install` command

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
